# Generated by Django 4.0.2 on 2022-03-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_cart_table_alter_cartitem_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.SmallIntegerField()),
                ('estimated_arrival_time', models.DateTimeField(null=True)),
                ('arrival_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'Order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'Orderitem',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'managed': False},
        ),
    ]
